// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmdYvm3bImQmUc9yzlvuOmZeU-pZRZUqk',
    appId: '1:970404459139:web:df00518dc32eb4d7f861b6',
    messagingSenderId: '970404459139',
    projectId: 'chatapp-9db18',
    authDomain: 'chatapp-9db18.firebaseapp.com',
    storageBucket: 'chatapp-9db18.firebasestorage.app',
    measurementId: 'G-J4HFPBTV42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvfyOgp_96WkPPXQH0NUpAxxTzt0iB3_I',
    appId: '1:970404459139:android:c237eaf82bbc28b1f861b6',
    messagingSenderId: '970404459139',
    projectId: 'chatapp-9db18',
    storageBucket: 'chatapp-9db18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS__Xr-ul_IaINO12bUXZ4lgoksnP1rDU',
    appId: '1:970404459139:ios:32f9fe6012f552c2f861b6',
    messagingSenderId: '970404459139',
    projectId: 'chatapp-9db18',
    storageBucket: 'chatapp-9db18.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS__Xr-ul_IaINO12bUXZ4lgoksnP1rDU',
    appId: '1:970404459139:ios:32f9fe6012f552c2f861b6',
    messagingSenderId: '970404459139',
    projectId: 'chatapp-9db18',
    storageBucket: 'chatapp-9db18.firebasestorage.app',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmdYvm3bImQmUc9yzlvuOmZeU-pZRZUqk',
    appId: '1:970404459139:web:4ae0b7fb0a223d52f861b6',
    messagingSenderId: '970404459139',
    projectId: 'chatapp-9db18',
    authDomain: 'chatapp-9db18.firebaseapp.com',
    storageBucket: 'chatapp-9db18.firebasestorage.app',
    measurementId: 'G-HZTZY85EQH',
  );
}
